gui:
  showIcons: true
  nerdFontsVersion: "3"

  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - default
    optionsTextColor:
      - default
    selectedLineBgColor:
      - default
git:
  diffRenderers:
    - colorArg: always
      command: ~/.config/git/delta-theme-wrapper
